# Generated by Django 2.1.7 on 2019-05-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('health', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('superpow', models.TextField()),
                ('starpower', models.TextField()),
                ('photo', models.URLField()),
            ],
        ),
    ]
